[package]
name = "id-generator"
version = "0.3.0"
edition = "2021"
description = "generate id"
repository = "https://github.com/get200/id-generator"
homepage = "https://github.com/get200/id-generator"
keywords = ["id", "generator", "snowflake"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
chrono = "0.4.19"
log = "0.4.17"
